### ISSUE TITLE
mailbox-server implementation

### ISSUE THREAD

**Issue by ghost** [JonathanLogan/covidtracer#7]
i thought on this a little bit and i like the idea for a simple `k/v` store since it's minimal and very fast. 

the part i'm not grasping is if we implement a deletion period of `x-days` do we introduce theoretical duplicate addresses somewhere or perhaps duplicate patients?

e.g:

- john catches a bug
- john has an address on the backend
- john recovers after x time
- john's information no longer needs to persist
- john goes to live a long life
- john 6 weeks later gets infected with a new pathogen
- john's address was deleted

would we consider it a new case, thus a new address?

also out of context a bit, if i'm thinking what you may be thinking this would be a good time to discuss async and time-delayed messaging.  

`edit: ok i read the mixer design spec, so this would likely cover async/time-delay`

@JonathanLogan @frankbraun

**Comment by JonathanLogan** [comment]
The addresses on the server are only for receiving messages, hence, if john recovers he sends his recovery status to his contacts. in the meantime, he collects new contacts. he then gets sick again and only contacts those collected in the timeframe before his new test.
